# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2014

# プレイヤーリスト上で、エントリーした人の名前に付ける色です。
entryColor: 'gold'

# 自動開始タイマー機能を使用するかどうかです。
# true = 使用する、false = 使用しない
autoStartTimer: false

# 自動開始タイマーを起動する人数です。
# 5 を設定したら、5人がエントリーした段階で、自動開始タイマーが起動します。
autoStartTimerPlayerNum: 5

# 自動開始タイマーの秒数です。
# 30 を設定したら、自動開始タイマーが起動してから30秒後にチーム分けが実行されます。
autoStartTimerSeconds: 30

# 自動開始タイマーが、自動開始を実行した時に、一緒に実行するコマンドです。
# /centry open コマンドを実行した時に使用されます。
autoStartTimerCommands: ['timer start ColorTeaming']

# 自動開始タイマーが、自動開始を実行した時に、一緒に実行するコマンドです。
# /centry open (コンフィグ名) コマンドを実行した時に使用されます。
# 例えば、config1 のコマンドを自動開始時に実行させたい場合は、
# /centry open config1 コマンドでエントリー受け付けを開始してください。
autoStartTimerCommandConfigs:
  config1: ['timer start ColorTeaming1']
  config2: ['timer start ColorTeaming2']

# 自動開始タイマーの動作モード設定です。
# NOTHING -> 自動開始を実行した時に、何もしないモード。
#     autoStartTimerCommands が設定されているなら、コマンドの実行のみが行われます。
# CLOSE_ONLY -> 自動開始を実行した時に、参加受け付けを締め切るモード。
# CLOSE_AND_TEAM -> 自動開始を実行した時に、参加受け付けを締め切り、
#     さらにチーム分けを行うモード(デフォルト)。
autoStartTimerMode: CLOSE_AND_TEAM

# ExpTimerでタイマーが動作しているときに、
# /centry open でエントリー受け付けを開始可能にするかどうかを設定します。
disableOpenOnRunningExpTimer: false
