# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2014



# -------------------- 共通設定 --------------------

# プレイヤーリスト上で、エントリーした人の名前に付ける色です。
entryColor: 'gold'

# エントリー済みでサーバーを離脱したプレイヤーを、エントリーから除去するかどうかです。
# true = 除去する、false = 除去しない
leaveOnQuitServer: true

# ExpTimerでタイマーが動作しているときに、
# /centry open でエントリー受け付けを開始可能にするかどうかを設定します。
disableOpenOnRunningExpTimer: false

# プレイヤーがエントリーしたときに実行するコマンドを設定します。
# 複数個のコマンドを設定することが可能です。コマンドはコンソール権限で実行されます。
# 使用できるキーワード：%player% エントリーしたプレイヤーのプレイヤー名です。
# 設定例： commandsOnJoin: ['tp %player% 100 70 200', 'say %player%さんがエントリーしました。']
commandsOnJoin: []

# エントリーしていたプレイヤーが離脱したときに実行するコマンドを設定します。
# 複数個のコマンドを設定することが可能です。コマンドはコンソール権限で実行されます。
# 使用できるキーワード：%player% 離脱したプレイヤーのプレイヤー名です。
# 設定例： commandsOnLeave: ['tp %player% 10 70 20', 'say %player%さんがエントリーをキャンセルしました。']
commandsOnLeave: []



# -------------------- 自動開始タイマー設定 --------------------

# 自動開始タイマー機能を使用するかどうかです。
# true = 使用する、false = 使用しない
autoStartTimer: false

# 自動開始タイマーを起動する人数です。
# 5 を設定したら、5人がエントリーした段階で、自動開始タイマーが起動します。
autoStartTimerPlayerNum: 5

# 自動開始タイマーの秒数です。
# 30 を設定したら、自動開始タイマーが起動してから30秒後にチーム分けが実行されます。
autoStartTimerSeconds: 30

# 自動開始タイマーが、自動開始を実行した時に、一緒に実行するコマンドです。
# /centry open コマンドを実行した時に使用されます。
autoStartTimerCommands: ['timer start ColorTeaming']

# 自動開始タイマーが、自動開始を実行した時に、一緒に実行するコマンドです。
# /centry open (コンフィグ名) コマンドを実行した時に使用されます。
# 例えば、config1 のコマンドを自動開始時に実行させたい場合は、
# /centry open config1 コマンドでエントリー受け付けを開始してください。
# /centry open random コマンドで、いずれかの設定がランダムで選択されて使用されます。
autoStartTimerCommandConfigs:
  config1: ['timer start ColorTeaming1']
  config2: ['timer start ColorTeaming2']

# 自動開始タイマーの動作モード設定です。
# NOTHING -> 自動開始を実行した時に、何もしないモード。
#     autoStartTimerCommands が設定されているなら、コマンドの実行のみが行われます。
# CLOSE_ONLY -> 自動開始を実行した時に、参加受け付けを締め切るモード。
# CLOSE_AND_TEAM -> 自動開始を実行した時に、参加受け付けを締め切り、
#     さらにチーム分けを行うモード(デフォルト)。
autoStartTimerMode: CLOSE_AND_TEAM
